<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Anime;
use App\Models\Episode;
use App\Models\Genre;
use App\Models\Studio;
use App\Models\Tag;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Cache;

class AnimeSeeder extends Seeder
{
    private function slug(string $title): string
    {
        return Str::slug($title, '-');
    }

    private function cover(string $seed): string
    {
        $images = [
            'aot-final' => 'https://cdn.myanimelist.net/images/anime/1948/120625.jpg',
            'jjk-s2' => 'https://cdn.myanimelist.net/images/anime/1792/138022.jpg',
            'demon-slayer' => 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
            'solo-leveling' => 'https://cdn.myanimelist.net/images/anime/1818/142492.jpg',
            'frieren' => 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
            'spy-family' => 'https://cdn.myanimelist.net/images/anime/1441/138018.jpg',
            'chainsaw-man' => 'https://cdn.myanimelist.net/images/anime/1806/126216.jpg',
            'mha-s7' => 'https://cdn.myanimelist.net/images/anime/1811/142888.jpg',
            'violet-evergarden' => 'https://cdn.myanimelist.net/images/anime/1795/95088.jpg',
            'one-piece' => 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg',
            'death-note' => 'https://cdn.myanimelist.net/images/anime/1079/138100.jpg',
            'naruto-shippuden' => 'https://cdn.myanimelist.net/images/anime/1565/111305.jpg',
            'haikyuu' => 'https://cdn.myanimelist.net/images/anime/7/76014.jpg',
            'spirited-away' => 'https://cdn.myanimelist.net/images/anime/6/79597.jpg',
            'mob-psycho' => 'https://cdn.myanimelist.net/images/anime/8/80356.jpg',
            'bocchi-rock' => 'https://cdn.myanimelist.net/images/anime/1448/127956.jpg',
            'kaguya-sama' => 'https://cdn.myanimelist.net/images/anime/1295/106551.jpg',
            'mushoku-tensei' => 'https://cdn.myanimelist.net/images/anime/1530/117776.jpg',
            'vinland-saga' => 'https://cdn.myanimelist.net/images/anime/1500/103005.jpg',
            'dr-stone' => 'https://cdn.myanimelist.net/images/anime/1613/138180.jpg',
            'steins-gate' => 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg',
            'fmab' => 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg',
            'code-geass' => 'https://cdn.myanimelist.net/images/anime/1032/135088.jpg',
            'cowboy-bebop' => 'https://cdn.myanimelist.net/images/anime/4/19644.jpg',
            'evangelion' => 'https://cdn.myanimelist.net/images/anime/1314/108941.jpg',
            'tokyo-ghoul' => 'https://cdn.myanimelist.net/images/anime/5/64449.jpg',
            'your-name' => 'https://cdn.myanimelist.net/images/anime/5/87048.jpg',
            'rezero' => 'https://cdn.myanimelist.net/images/anime/1522/128039.jpg',
            'hxh' => 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg',
            'bleach-tybw' => 'https://cdn.myanimelist.net/images/anime/1908/135431.jpg',
            'aot-s1' => 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
            'sao' => 'https://cdn.myanimelist.net/images/anime/11/39797.jpg',
            'opm' => 'https://cdn.myanimelist.net/images/anime/12/76049.jpg',
            'toradora' => 'https://cdn.myanimelist.net/images/anime/13/22128.jpg',
            'jojo' => 'https://cdn.myanimelist.net/images/anime/1286/138142.jpg',
            'made-in-abyss' => 'https://cdn.myanimelist.net/images/anime/6/86733.jpg',
            'promised-neverland' => 'https://cdn.myanimelist.net/images/anime/1830/118780.jpg',
            'food-wars' => 'https://cdn.myanimelist.net/images/anime/1324/126249.jpg',
            'weathering-with-you' => 'https://cdn.myanimelist.net/images/anime/1880/101146.jpg',
            'dandadan' => 'https://cdn.myanimelist.net/images/anime/1833/143460.jpg',
        ];

        return $images[$seed] ?? 'https://cdn.myanimelist.net/images/anime/1948/120625.jpg';
    }

    public function run(): void
    {
        $studios = Studio::all()->keyBy('name');
        $genres = Genre::all()->keyBy('name');

        $animeList = [
            [
                'title' => 'Attack on Titan: The Final Season',
                'title_english' => 'Attack on Titan Final Season',
                'title_japanese' => '進撃の巨人 The Final Season',
                'synopsis' => 'After uncovering the truth about the world beyond the walls, Eren Yeager and the Survey Corps face their greatest challenge yet. As Marley and Paradis island clash, the fate of humanity hangs in the balance.',
                'cover_image' => $this->cover('aot-final'),
                'studio' => 'MAPPA',
                'genres' => ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Winter',
                'year' => 2023,
                'episodes_count' => 28,
                'score' => 9.1,
                'score_count' => 15234,
                'views_count' => 2500000,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'title' => 'Jujutsu Kaisen Season 2',
                'title_english' => 'Jujutsu Kaisen 2nd Season',
                'title_japanese' => '呪術廻戦 第2期',
                'synopsis' => 'The story follows Yuji Itadori and his fellow sorcerers as they face powerful curses. Season 2 covers the Hidden Inventory/Premature Death arc and the Shibuya Incident arc.',
                'cover_image' => $this->cover('jjk-s2'),
                'studio' => 'MAPPA',
                'genres' => ['Action', 'Supernatural', 'School'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Summer',
                'year' => 2023,
                'episodes_count' => 23,
                'score' => 8.9,
                'score_count' => 12500,
                'views_count' => 1800000,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba',
                'title_english' => 'Demon Slayer',
                'title_japanese' => '鬼滅の刃',
                'synopsis' => 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
                'cover_image' => $this->cover('demon-slayer'),
                'studio' => 'Ufotable',
                'genres' => ['Action', 'Fantasy', 'Supernatural'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2019,
                'episodes_count' => 26,
                'score' => 8.7,
                'score_count' => 18900,
                'views_count' => 3200000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Solo Leveling',
                'title_english' => 'Solo Leveling',
                'title_japanese' => '俺だけレベルアップな件',
                'synopsis' => 'In a world where hunters — human warriors who possess magical abilities — must battle deadly monsters to protect the human race, Sung Jinwoo, the weakest hunter, finds a hidden dungeon with the hardest rules that will change his life.',
                'cover_image' => $this->cover('solo-leveling'),
                'studio' => 'A-1 Pictures',
                'genres' => ['Action', 'Adventure', 'Fantasy'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Winter',
                'year' => 2024,
                'episodes_count' => 12,
                'score' => 8.5,
                'score_count' => 9800,
                'views_count' => 1500000,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'title' => 'Frieren: Beyond Journey\'s End',
                'title_english' => 'Frieren: Beyond Journey\'s End',
                'title_japanese' => '葬送のフリーレン',
                'synopsis' => 'After the party of heroes defeated the Demon King, the elf mage Frieren embarks on a journey to understand humanity and the meaning of life after her companions pass away.',
                'cover_image' => $this->cover('frieren'),
                'studio' => 'Madhouse',
                'genres' => ['Adventure', 'Drama', 'Fantasy'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2023,
                'episodes_count' => 28,
                'score' => 9.3,
                'score_count' => 11200,
                'views_count' => 1200000,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'title' => 'Spy x Family Season 2',
                'title_english' => 'Spy x Family Part 2',
                'title_japanese' => 'SPY×FAMILY Season 2',
                'synopsis' => 'Master spy Twilight continues his mission to maintain world peace by posing as a family man, all while his adopted daughter is a telepath and his wife is an assassin.',
                'cover_image' => $this->cover('spy-family'),
                'studio' => 'Wit Studio',
                'genres' => ['Action', 'Comedy', 'Slice of Life'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2023,
                'episodes_count' => 12,
                'score' => 8.4,
                'score_count' => 8900,
                'views_count' => 1100000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Chainsaw Man',
                'title_english' => 'Chainsaw Man',
                'title_japanese' => 'チェンソーマン',
                'synopsis' => 'Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses.',
                'cover_image' => $this->cover('chainsaw-man'),
                'studio' => 'MAPPA',
                'genres' => ['Action', 'Horror', 'Supernatural'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2022,
                'episodes_count' => 12,
                'score' => 8.6,
                'score_count' => 14200,
                'views_count' => 1900000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'My Hero Academia Season 7',
                'title_english' => 'Boku no Hero Academia 7th Season',
                'title_japanese' => '僕のヒーローアカデミア 第7期',
                'synopsis' => 'The final war between heroes and villains reaches its climax as Deku and his classmates face off against All For One and Shigaraki in an epic battle for the fate of society.',
                'cover_image' => $this->cover('mha-s7'),
                'studio' => 'Bones',
                'genres' => ['Action', 'School', 'Supernatural'],
                'type' => 'TV',
                'status' => 'ongoing',
                'season' => 'Spring',
                'year' => 2024,
                'episodes_count' => 21,
                'score' => 8.2,
                'score_count' => 7600,
                'views_count' => 980000,
                'is_featured' => false,
                'is_trending' => true,
            ],
            [
                'title' => 'Violet Evergarden',
                'title_english' => 'Violet Evergarden',
                'title_japanese' => 'ヴァイオレット・エヴァーガーデン',
                'synopsis' => 'A former soldier becomes an Auto Memory Doll, writing letters for others, in order to understand the meaning of the words "I love you" spoken to her by her commanding officer.',
                'cover_image' => $this->cover('violet-evergarden'),
                'studio' => 'Kyoto Animation',
                'genres' => ['Drama', 'Fantasy', 'Slice of Life'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Winter',
                'year' => 2018,
                'episodes_count' => 13,
                'score' => 8.7,
                'score_count' => 6500,
                'views_count' => 750000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'One Piece',
                'title_english' => 'One Piece',
                'title_japanese' => 'ワンピース',
                'synopsis' => 'Monkey D. Luffy sets off on an adventure with his pirate crew in hopes of finding the greatest treasure ever, known as "One Piece", and becoming the next Pirate King.',
                'cover_image' => $this->cover('one-piece'),
                'studio' => 'Toei Animation',
                'genres' => ['Action', 'Adventure', 'Comedy', 'Fantasy'],
                'type' => 'TV',
                'status' => 'ongoing',
                'season' => null,
                'year' => 1999,
                'episodes_count' => 1100,
                'score' => 8.9,
                'score_count' => 25000,
                'views_count' => 5000000,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'title' => 'Death Note',
                'title_english' => 'Death Note',
                'title_japanese' => 'デスノート',
                'synopsis' => 'A high school student discovers a supernatural notebook that allows him to kill anyone by writing the victim\'s name while picturing their face. He decides to cleanse the world of evil.',
                'cover_image' => $this->cover('death-note'),
                'studio' => 'Madhouse',
                'genres' => ['Mystery', 'Psychological', 'Supernatural', 'Thriller'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2006,
                'episodes_count' => 37,
                'score' => 9.0,
                'score_count' => 32000,
                'views_count' => 4200000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Naruto Shippuden',
                'title_english' => 'Naruto Shippuden',
                'title_japanese' => 'ナルト 疾風伝',
                'synopsis' => 'Naruto Uzumaki returns after two and a half years of training with a new goal: to save his friend Sasuke from the darkness and protect the Hidden Leaf Village.',
                'cover_image' => $this->cover('naruto-shippuden'),
                'studio' => 'Studio Pierrot',
                'genres' => ['Action', 'Adventure', 'Martial Arts'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Winter',
                'year' => 2007,
                'episodes_count' => 500,
                'score' => 8.6,
                'score_count' => 28000,
                'views_count' => 4800000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Haikyuu!!',
                'title_english' => 'Haikyu!!',
                'title_japanese' => 'ハイキュー!!',
                'synopsis' => 'Inspired by a small-statured volleyball player, Shoyo Hinata joins his high school volleyball team and aims to become a great player despite his height disadvantage.',
                'cover_image' => $this->cover('haikyuu'),
                'studio' => 'Production I.G',
                'genres' => ['Sports', 'School', 'Comedy', 'Drama'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2014,
                'episodes_count' => 25,
                'score' => 8.8,
                'score_count' => 11000,
                'views_count' => 920000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Spirited Away',
                'title_english' => 'Spirited Away',
                'title_japanese' => '千と千尋の神隠し',
                'synopsis' => 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.',
                'cover_image' => $this->cover('spirited-away'),
                'studio' => 'Studio Ghibli',
                'genres' => ['Adventure', 'Fantasy', 'Supernatural'],
                'type' => 'Movie',
                'status' => 'completed',
                'season' => null,
                'year' => 2001,
                'episodes_count' => 1,
                'score' => 9.2,
                'score_count' => 21000,
                'views_count' => 1500000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Mob Psycho 100',
                'title_english' => 'Mob Psycho 100',
                'title_japanese' => 'モブサイコ100',
                'synopsis' => 'Shigeo "Mob" Kageyama is an esper with tremendous psychic abilities. He works for a fake psychic while trying to live a normal life and keep his powers under control.',
                'cover_image' => $this->cover('mob-psycho'),
                'studio' => 'Bones',
                'genres' => ['Action', 'Comedy', 'Supernatural'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Summer',
                'year' => 2016,
                'episodes_count' => 12,
                'score' => 8.6,
                'score_count' => 8200,
                'views_count' => 680000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Bocchi the Rock!',
                'title_english' => 'Bocchi the Rock!',
                'title_japanese' => 'ぼっち・ざ・ろっく！',
                'synopsis' => 'Hitori Gotoh is a loner high school girl who spends her days practicing guitar. She dreams of joining a band but lacks social skills. One day, she joins the Kessoku Band.',
                'cover_image' => $this->cover('bocchi-rock'),
                'studio' => 'CloverWorks',
                'genres' => ['Comedy', 'Slice of Life', 'School'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2022,
                'episodes_count' => 12,
                'score' => 8.8,
                'score_count' => 7100,
                'views_count' => 540000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Kaguya-sama: Love is War',
                'title_english' => 'Kaguya-sama: Love is War',
                'title_japanese' => 'かぐや様は告らせたい～天才たちの恋愛頭脳戦～',
                'synopsis' => 'Two prideful geniuses, Miyuki Shirogane and Kaguya Shinomiya, lead the prestigious Shuchiin Academy\'s student council. Both are in love but too proud to confess, leading to hilarious mind games.',
                'cover_image' => $this->cover('kaguya-sama'),
                'studio' => 'A-1 Pictures',
                'genres' => ['Comedy', 'Romance', 'School', 'Psychological'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2019,
                'episodes_count' => 12,
                'score' => 8.7,
                'score_count' => 9500,
                'views_count' => 720000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Mushoku Tensei: Jobless Reincarnation',
                'title_english' => 'Mushoku Tensei: Jobless Reincarnation',
                'title_japanese' => '無職転生 〜異世界行ったら本気だす〜',
                'synopsis' => 'A 34-year-old NEET is reincarnated into a magical world as Rudeus Greyrat. Determined to live his new life without regrets, he uses his past knowledge and magical talent to become powerful.',
                'cover_image' => $this->cover('mushoku-tensei'),
                'studio' => 'Studio Pierrot',
                'genres' => ['Adventure', 'Drama', 'Fantasy', 'Isekai'],
                'type' => 'TV',
                'status' => 'ongoing',
                'season' => 'Spring',
                'year' => 2024,
                'episodes_count' => 12,
                'score' => 8.5,
                'score_count' => 8800,
                'views_count' => 850000,
                'is_featured' => false,
                'is_trending' => true,
            ],
            [
                'title' => 'Vinland Saga',
                'title_english' => 'Vinland Saga',
                'title_japanese' => 'ヴィンランド・サガ',
                'synopsis' => 'Young Thorfinn grows up hearing tales of Vinland, a warm and fertile land. After his father is killed, he joins a group of mercenaries, seeking revenge against his father\'s killer.',
                'cover_image' => $this->cover('vinland-saga'),
                'studio' => 'Wit Studio',
                'genres' => ['Action', 'Adventure', 'Drama'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Summer',
                'year' => 2019,
                'episodes_count' => 24,
                'score' => 8.8,
                'score_count' => 7800,
                'views_count' => 620000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Dr. Stone: New World',
                'title_english' => 'Dr. Stone: New World',
                'title_japanese' => 'ドクターストーン NEW WORLD',
                'synopsis' => 'After humanity is petrified for thousands of years, genius high schooler Senku awakens and begins rebuilding civilization from scratch using the power of science.',
                'cover_image' => $this->cover('dr-stone'),
                'studio' => 'TMS Entertainment',
                'genres' => ['Adventure', 'Comedy', 'Sci-Fi'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2023,
                'episodes_count' => 22,
                'score' => 8.3,
                'score_count' => 5600,
                'views_count' => 480000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Steins;Gate',
                'title_english' => 'Steins;Gate',
                'title_japanese' => 'シュタインズ・ゲート',
                'synopsis' => 'A group of friends discover a way to send text messages to the past, inadvertently changing the present. As they experiment with time travel, they uncover a conspiracy that threatens the fabric of reality.',
                'cover_image' => $this->cover('steins-gate'),
                'studio' => 'Madhouse',
                'genres' => ['Sci-Fi', 'Psychological', 'Thriller', 'Drama'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2011,
                'episodes_count' => 24,
                'score' => 9.1,
                'score_count' => 28000,
                'views_count' => 1800000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Fullmetal Alchemist: Brotherhood',
                'title_english' => 'Fullmetal Alchemist: Brotherhood',
                'title_japanese' => '鋼の錬金術師 BROTHERHOOD',
                'synopsis' => 'Two brothers search for the Philosopher\'s Stone to restore their bodies after a failed alchemical experiment. Their journey uncovers a vast conspiracy that threatens the entire nation.',
                'cover_image' => $this->cover('fmab'),
                'studio' => 'Bones',
                'genres' => ['Action', 'Adventure', 'Fantasy', 'Drama'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2009,
                'episodes_count' => 64,
                'score' => 9.2,
                'score_count' => 35000,
                'views_count' => 3800000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Code Geass',
                'title_english' => 'Code Geass: Lelouch of the Rebellion',
                'title_japanese' => 'コードギアス 反逆のルルーシュ',
                'synopsis' => 'After being given the power of Geass, Lelouch vi Britannia leads a rebellion against the Holy Britannian Empire that conquered Japan, using his strategic genius and supernatural ability.',
                'cover_image' => $this->cover('code-geass'),
                'studio' => 'Sunrise',
                'genres' => ['Action', 'Sci-Fi', 'Mecha', 'Psychological'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2006,
                'episodes_count' => 25,
                'score' => 8.9,
                'score_count' => 19000,
                'views_count' => 1600000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Cowboy Bebop',
                'title_english' => 'Cowboy Bebop',
                'title_japanese' => 'カウボーイビバップ',
                'synopsis' => 'In the year 2071, bounty hunters Spike Spiegel and Jet Black travel the solar system in their ship Bebop, tracking down criminals while confronting their own pasts.',
                'cover_image' => $this->cover('cowboy-bebop'),
                'studio' => 'Sunrise',
                'genres' => ['Action', 'Sci-Fi', 'Drama'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 1998,
                'episodes_count' => 26,
                'score' => 8.9,
                'score_count' => 16000,
                'views_count' => 1200000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Neon Genesis Evangelion',
                'title_english' => 'Neon Genesis Evangelion',
                'title_japanese' => '新世紀エヴァンゲリオン',
                'synopsis' => 'In a post-apocalyptic world, teenager Shinji Ikari is recruited by his father to pilot a giant bio-machine mecha called an Evangelion to combat mysterious beings known as Angels.',
                'cover_image' => $this->cover('evangelion'),
                'studio' => 'Gainax',
                'genres' => ['Sci-Fi', 'Mecha', 'Psychological', 'Drama'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 1995,
                'episodes_count' => 26,
                'score' => 8.5,
                'score_count' => 14000,
                'views_count' => 950000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Tokyo Ghoul',
                'title_english' => 'Tokyo Ghoul',
                'title_japanese' => '東京喰種トーキョーグール',
                'synopsis' => 'College student Ken Kaneki is transformed into a half-ghoul after a deadly encounter. Caught between the human and ghoul worlds, he must navigate his new identity and survival.',
                'cover_image' => $this->cover('tokyo-ghoul'),
                'studio' => 'Studio Pierrot',
                'genres' => ['Action', 'Horror', 'Supernatural', 'Psychological'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Summer',
                'year' => 2014,
                'episodes_count' => 12,
                'score' => 8.0,
                'score_count' => 17000,
                'views_count' => 2100000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Your Name',
                'title_english' => 'Your Name',
                'title_japanese' => '君の名は。',
                'synopsis' => 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.',
                'cover_image' => $this->cover('your-name'),
                'studio' => 'CloverWorks',
                'genres' => ['Romance', 'Drama', 'Fantasy'],
                'type' => 'Movie',
                'status' => 'completed',
                'season' => null,
                'year' => 2016,
                'episodes_count' => 1,
                'score' => 9.0,
                'score_count' => 22000,
                'views_count' => 2800000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Re:Zero − Starting Life in Another World',
                'title_english' => 'Re:Zero',
                'title_japanese' => 'Re:ゼロから始める異世界生活',
                'synopsis' => 'Subaru Natsuki is transported to a fantasy world where he discovers he has the ability to reverse time by dying. He uses this power to protect those he cares about, facing unimaginable hardships.',
                'cover_image' => $this->cover('rezero'),
                'studio' => 'Wit Studio',
                'genres' => ['Isekai', 'Fantasy', 'Drama', 'Psychological', 'Thriller'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2016,
                'episodes_count' => 25,
                'score' => 8.4,
                'score_count' => 13500,
                'views_count' => 1100000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Hunter x Hunter (2011)',
                'title_english' => 'Hunter x Hunter',
                'title_japanese' => 'ハンター×ハンター',
                'synopsis' => 'Gon Freecss aspires to become a Hunter, an elite member of humanity who can track down secret treasures, rare beasts, or even other individuals, to find his father who abandoned him.',
                'cover_image' => $this->cover('hxh'),
                'studio' => 'Madhouse',
                'genres' => ['Action', 'Adventure', 'Fantasy'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2011,
                'episodes_count' => 148,
                'score' => 9.1,
                'score_count' => 24000,
                'views_count' => 2200000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Bleach: Thousand-Year Blood War',
                'title_english' => 'Bleach: TYBW',
                'title_japanese' => 'BLEACH 千年血戦篇',
                'synopsis' => 'The peace is suddenly broken when warning sirens blare through the Soul Society. Residents there are disappearing without a trace and nobody knows who is behind it. A dark war begins.',
                'cover_image' => $this->cover('bleach-tybw'),
                'studio' => 'Studio Pierrot',
                'genres' => ['Action', 'Adventure', 'Supernatural'],
                'type' => 'TV',
                'status' => 'ongoing',
                'season' => 'Summer',
                'year' => 2024,
                'episodes_count' => 26,
                'score' => 8.7,
                'score_count' => 8900,
                'views_count' => 950000,
                'is_featured' => true,
                'is_trending' => true,
            ],
            [
                'title' => 'Attack on Titan',
                'title_english' => 'Attack on Titan',
                'title_japanese' => '進撃の巨人',
                'synopsis' => 'In a world where humanity lives within enormous walled cities to protect themselves from Titans, gigantic humanoid creatures, young Eren Yeager vows to cleanse the earth of these creatures after they destroy his hometown.',
                'cover_image' => $this->cover('aot-s1'),
                'studio' => 'Wit Studio',
                'genres' => ['Action', 'Drama', 'Fantasy', 'Mystery'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2013,
                'episodes_count' => 25,
                'score' => 8.8,
                'score_count' => 30000,
                'views_count' => 3500000,
                'is_featured' => true,
                'is_trending' => false,
            ],
            [
                'title' => 'Sword Art Online',
                'title_english' => 'Sword Art Online',
                'title_japanese' => 'ソードアート・オンライン',
                'synopsis' => 'In the year 2022, thousands of gamers are trapped in a virtual reality MMORPG and discover that dying in the game means dying in real life. Kirito must clear all 100 floors to free everyone.',
                'cover_image' => $this->cover('sao'),
                'studio' => 'A-1 Pictures',
                'genres' => ['Action', 'Adventure', 'Fantasy', 'Romance'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Summer',
                'year' => 2012,
                'episodes_count' => 25,
                'score' => 7.6,
                'score_count' => 20000,
                'views_count' => 2600000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'One Punch Man',
                'title_english' => 'One Punch Man',
                'title_japanese' => 'ワンパンマン',
                'synopsis' => 'Saitama is a hero who can defeat any opponent with a single punch, but his overwhelming power has made him bored with being a hero. He searches for a worthy opponent.',
                'cover_image' => $this->cover('opm'),
                'studio' => 'Madhouse',
                'genres' => ['Action', 'Comedy', 'Supernatural'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2015,
                'episodes_count' => 12,
                'score' => 8.7,
                'score_count' => 18000,
                'views_count' => 1700000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Toradora!',
                'title_english' => 'Toradora!',
                'title_japanese' => 'とらドラ！',
                'synopsis' => 'Ryuuji Takasu and Taiga Aisaka form an unlikely alliance to help each other confess to their respective crushes, but their plan takes unexpected turns as they grow closer to each other.',
                'cover_image' => $this->cover('toradora'),
                'studio' => 'J.C.Staff',
                'genres' => ['Comedy', 'Romance', 'School', 'Slice of Life'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2008,
                'episodes_count' => 25,
                'score' => 8.2,
                'score_count' => 11000,
                'views_count' => 680000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'JoJo\'s Bizarre Adventure',
                'title_english' => 'JoJo\'s Bizarre Adventure',
                'title_japanese' => 'ジョジョの奇妙な冒険',
                'synopsis' => 'The story of the Joestar family, who are possessed with unique powers, and their battles against supernatural forces across generations.',
                'cover_image' => $this->cover('jojo'),
                'studio' => 'David Production',
                'genres' => ['Action', 'Adventure', 'Supernatural'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Fall',
                'year' => 2012,
                'episodes_count' => 26,
                'score' => 8.4,
                'score_count' => 14500,
                'views_count' => 1300000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Made in Abyss',
                'title_english' => 'Made in Abyss',
                'title_japanese' => 'メイドインアビス',
                'synopsis' => 'An orphan girl named Riko dreams of following in her mother\'s footsteps as a Cave Raider and solving the mystery of the Abyss, a massive chasm filled with ancient relics and dangerous creatures.',
                'cover_image' => $this->cover('made-in-abyss'),
                'studio' => 'Kyoto Animation',
                'genres' => ['Adventure', 'Fantasy', 'Sci-Fi', 'Mystery'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Summer',
                'year' => 2017,
                'episodes_count' => 13,
                'score' => 8.7,
                'score_count' => 8500,
                'views_count' => 560000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'The Promised Neverland',
                'title_english' => 'The Promised Neverland',
                'title_japanese' => '約束のネバーランド',
                'synopsis' => 'A group of orphans living in an idyllic orphanage discover the dark truth behind their existence and plan a daring escape before it\'s too late.',
                'cover_image' => $this->cover('promised-neverland'),
                'studio' => 'CloverWorks',
                'genres' => ['Mystery', 'Thriller', 'Sci-Fi', 'Horror'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Winter',
                'year' => 2019,
                'episodes_count' => 12,
                'score' => 8.5,
                'score_count' => 9200,
                'views_count' => 780000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Food Wars! Shokugeki no Soma',
                'title_english' => 'Food Wars!',
                'title_japanese' => '食戟のソーマ',
                'synopsis' => 'Yukihira Soma enrolls in an elite culinary school where students engage in intense cooking battles called shokugeki. He aims to surpass his father and become the best chef.',
                'cover_image' => $this->cover('food-wars'),
                'studio' => 'J.C.Staff',
                'genres' => ['Comedy', 'School', 'Slice of Life'],
                'type' => 'TV',
                'status' => 'completed',
                'season' => 'Spring',
                'year' => 2015,
                'episodes_count' => 24,
                'score' => 8.2,
                'score_count' => 9800,
                'views_count' => 820000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Weathering with You',
                'title_english' => 'Weathering with You',
                'title_japanese' => '天気の子',
                'synopsis' => 'A high-school boy who has run away to Tokyo befriends a girl who appears to be able to manipulate the weather. They soon discover that her power has consequences.',
                'cover_image' => $this->cover('weathering-with-you'),
                'studio' => 'CloverWorks',
                'genres' => ['Romance', 'Drama', 'Fantasy'],
                'type' => 'Movie',
                'status' => 'completed',
                'season' => null,
                'year' => 2019,
                'episodes_count' => 1,
                'score' => 8.4,
                'score_count' => 13000,
                'views_count' => 980000,
                'is_featured' => false,
                'is_trending' => false,
            ],
            [
                'title' => 'Dandadan',
                'title_english' => 'Dandadan',
                'title_japanese' => 'ダンダダン',
                'synopsis' => 'Momo Ayase believes in ghosts but not aliens, while Okarun believes in aliens but not ghosts. When they test each other\'s beliefs, they discover both are real and gain supernatural powers.',
                'cover_image' => $this->cover('dandadan'),
                'studio' => 'MAPPA',
                'genres' => ['Action', 'Comedy', 'Supernatural', 'Romance'],
                'type' => 'TV',
                'status' => 'ongoing',
                'season' => 'Fall',
                'year' => 2024,
                'episodes_count' => 12,
                'score' => 8.3,
                'score_count' => 6200,
                'views_count' => 720000,
                'is_featured' => false,
                'is_trending' => true,
            ],
        ];

        foreach ($animeList as $data) {
            $studio = $studios->get($data['studio']);
            $genreNames = $data['genres'];
            unset($data['studio'], $data['genres']);

            $data['slug'] = $this->slug($data['title']);
            $data['studio_id'] = $studio?->id;
            $data['rating'] = 'PG-13';

            $anime = Anime::create($data);

            foreach ($genreNames as $genreName) {
                $genre = $genres->get($genreName);
                if ($genre) {
                    $anime->genres()->attach($genre->id);
                }
            }

            $epCount = min($data['episodes_count'], 5);
            for ($i = 1; $i <= $epCount; $i++) {
                Episode::create([
                    'anime_id' => $anime->id,
                    'title' => "Episode $i",
                    'number' => $i,
                    'synopsis' => "Episode $i of {$data['title']}.",
                    'duration' => 1440,
                    'is_subbed' => true,
                    'is_dubbed' => ($i % 3 === 0),
                ]);
            }
        }

        // Clear all homepage caches
        Cache::forget('hero_anime');
        Cache::forget('hero_anime_fallback');
        Cache::forget('trending_anime');
        Cache::forget('top_rated_anime');
        Cache::forget('genre_sections');
        Cache::forget('upcoming_anime');
    }
}
